### ISSUE TITLE
Suggestion: Shouldn't be a git repository if you only want to use this package

### ISSUE THREAD

**Issue by rizken** [bjornet/jirabranchcreator#3]
I want to be able to download this package without it being a git repository. 

Suggestion: make use of [degit](https://www.npmjs.com/package/degit?activeTab=readme) instead of git clone. 

Current
`git clone git@github.com:bjornet/jirabranchcreator.git`

Wanted
`degit bjornet/jirabranchcreator`

**Comment by bjornet** [comment]
Resolves with #21
