### ISSUE TITLE
Make sure TTB can complete the ESSENTIAL step of creating a local branch

### ISSUE THREAD

**Issue by bjornet** [bjornet/jirabranchcreator#34]
As a user, when a "nice to have" feature goes wrong, I want the program tell me what went wrong but still do the essential steps.

### Acceptance criteria
- it should check if a branch already exists 
- it should tell the user if it failed to create a linked branch
- it should checkout a local branch:
  - if branch already exists
  - or it failed to create a linked branch

### Notes
Message from Fille > "Jag skapade en Classic Personal Access Token och körde i alla permissions för att testa, men får följande fel:"

**Comment by rizken** [comment]
Everyone with repository write access can create a linked branch according to [githubs documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-a-branch-for-an-issue#creating-a-branch-for-an-issue)
